name: Oh-ShINT
channels:
  - defaults
dependencies:
  - certifi
  - conda-forge::pandas=3.0.0
  - conda-forge::regex=2026.1.15
  - conda-forge::rich=14.3.2
  - conda-forge::tinydb=4.8.2
  - conda-forge::typer=0.21.1
  - httpx=0.28.1
  - jsonpath-ng=1.7.0
  - loguru=0.7.3
  - pip=25.3
  - pycountry=24.6.1
  - python-dotenv=1.2.1
  - python=3.12.9
  - pytz=2025.2
  - typing_extensions=4.15.0
  - pip:
    - hishel[httpx]==1.1.9
    - tinydb-serialization==2.2.0